---
title: "Investigation of Finger Lengths by Sex"
output: html_document
---


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(RColorBrewer)
library(ggplot2)
library(dplyr)
library(readr)
library(knitr)
library(kableExtra)

df <- read_csv("ringData.csv")

smry<-
  df %>%
  group_by(Sex) %>%
  summarise(obs=n(), mean_length = round(mean(Length),2), s.dev=round(sd(Length),2), var=round(var(Length),2) )

correlation <- cor(df$Age,df$Length)

num_men<-df %>% filter(Sex=="M")  %>% summarise(n())
num_women<-df %>% filter(Sex=="F")  %>% summarise(n())

colors<-c("#5d9cd6","#6ca844")

bp<-ggplot(data=df, aes(x=Sex, y=Length, fill=Sex))

scat<-ggplot(data=df,aes(y=Length, x=Age))  


```
##Mthodology
We sampled  finger lengths of `r num_men` and `r num_women` aged between `r min(df$Age)` and `r max(df$Age)`

Age might me considered a conounding factor. An initial exploration of the data shows little correlation between age and finger lenths with $R^2=$ `r round(correlation,3)` so we can dismiss this as a possible issue.  The scatter graph conirst this to be so. 

```{r echo=FALSE, message=FALSE}
scat+geom_point(size=4, shape=18) + theme_classic()+
  #stat_smooth(method = "lm", se=FALSE)+
  #facet_grid(Sex ~ .)
  #geom_smooth(method="lm", se=FALSE, color="black", linetype="dashed")+
  geom_hline(yintercept = mean(df$Length), linetype="dashed", size=1)+
  scale_color_manual(values=colors)+
  theme_classic()+
  theme(axis.title.y = element_text(),   legend.position = "top", plot.title=element_text(hjust=0.5, size=20))+
  labs(x="Age \\Years", y="Finger length \\cm", title = "Finger length against age")+
  annotate(geom = "text", x = 17, y =  mean(df$Length)+1, label = round(mean(df$Length),2))
```

##Results
```{r results="asis", echo=FALSE, message=FALSE}
kable(smry) %>%
 kable_styling(position = "center")

```
##
##  
    



```{r echo=FALSE, message=FALSE}
hist<-ggplot(data=df,aes(x=Length, fill=Sex, color=Sex))

hist + geom_histogram(bins =7, position="dodge", size = 0.6)+
  labs(x="Finger length \\cm", y="", title = "Finger length frequency by sex")+
  scale_fill_manual(values=colors)+
  scale_color_manual(values=c("blue", "dark green"))+
  theme_classic()+
  theme(legend.position = "top", plot.title=element_text(hjust=0.5, size=20))

bp<-ggplot(data=df,aes(x=Sex,y=Length, fill=Sex))  

bp+geom_boxplot()+
  geom_jitter(width=0.2)+
  scale_fill_manual(values=colors)+
  theme_classic()+
  theme(legend.position = "top", plot.title=element_text(hjust=0.5, size=20))+
  coord_flip()+
  labs(y="length \\cm", x=" ", title="Boxplot of finger length by sex")
```

  
    
```{r  echo=FALSE, message=FALSE, warning=FALSE}
t.test(Length~Sex, data = df, var.equal=TRUE, mu=0)
```